config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/create', to: 'home#create'
  post '/create/progress', to: 'home#create_prog', as: 'createProgress'
  get '/:blog_id/edit', to: 'home#update', as: 'edit'
  patch '/:getId/edit/progress', to: 'home#update_prog', as: 'updateProgress'
  delete '/:getId/delete', to: 'home#destroy', as: 'destroyProgress'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cbi_blog.rb
class CbiBlog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @table = CbiBlog.all.order(updated_at: :desc)
    end
 
    def create
        @rand = SecureRandom.urlsafe_base64(nil, false)
        @new = CbiBlog.new
    end

    def create_prog
        @table = CbiBlog.new(form_params)
        if @table.save
            redirect_to root_path, notice: 'Create blog success'
        else
            render :create
        end
    end
 
    def update
        @id = CbiBlog.find(params[:blog_id])        
    end

    def update_prog
        @id = CbiBlog.find(params[:getId])
        if @id.update(form_params)
            redirect_to root_path, notice: 'Update blog success'
        else
            render :update
        end
    end
 
    def show
        
    end
 
    def destroy
        @table = CbiBlog.find(find_params)
        if @table.destroy
            redirect_to root_path, notice: 'Delete '+ find_params() +' success'
        else
            render :index
        end
    end
 
    private
    def find_blog
        Blog.find(params[:id])
    end

    private
    def form_params
        params.require(:cbi_blog).permit(:blog_id, :blog_title, :blog_desc)
    end

    private
    def find_params
        params[:getId]
    end
 end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/create.html.erb
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Create</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <%= link_to root_path do 'Home' end %>
                    </li>
                    <li class="breadcrumb-item active">
                        <%= link_to create_path do 'Create' end %>
                    </li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Create new Blog</h3>
                    </div>

                    <%= form_for (@new), url: createProgress_path do |f| %>
                    <div class="card-body">
                        
                        <div class="form-group">
                            <%= f.label 'Title', for: 'cbiTitle' %>
                            <%= f.text_field :blog_title, name: 'title', class: 'form-control', id: 'cbiTitle', placeholder: 'Title', required: '' %>
                        </div>
                        <div class="form-group">
                            <label for="cbiDesc">Description</label>
                            <textarea name="desc" class="form-control" id="cbiDesc" placeholder="Description" required></textarea>
                            <%= f.label 'Description', for: 'cbiDesc' %>
                            <%= f.text_area :blog_desc, name: 'title', class: 'form-control', id: 'cbiTitle', placeholder: 'Title', required: '' %>
                        </div>

                        <button type="submit" class="btn btn-primary btn-block">Save</button>

                    </div>
                    <% end %>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Home</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <%= link_to root_path do 'Home' end %>
                    </li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<div class="content container-fluid">
    <div class="container-fluid">
        
        <% if notice %>
            <div class="alert alert-success">
            <%= notice %>
            </div>
        <% end %>

        <div class="row">
            <div class="col-md-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Blog</h3>
                    </div>
                    <div class="card-body p-0">
                        <table class="table table-sm">
                            <thead>
                                <tr class="bg-primary">
                                    <th style="width: 10px">#</th>
                                    <th>Title</th>
                                    <th>Desc</th>
                                    <th colspan="2"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @table.each_with_index do |data, no| %>
                                <tr>
                                    <td><%= no+=1 %></td>
                                    <td><%= data.blog_title %></td>
                                    <td><%= data.blog_desc %></td>
                                    <td class="bg-info text-center p-0 px-1 pt-1">
                                        <%= link_to edit_path(data.blog_id) do %>
                                            <i class="fas fa-pen"></i>
                                        <% end %>
                                    </td>
                                    <td class="bg-danger text-center p-0 px-1 pt-1">
                                        <%= link_to destroyProgress_path(data.id), data: { confirm: 'Want to delete ?' }, method: :delete do %>
                                            <i class="fas fa-trash"></i>
                                        <% end %>
                                    </td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>

app/views/home/update.html.erb
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Create</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <%= link_to root_path do 'Home' end %>
                    </li>
                    <li class="breadcrumb-item active">
                        <%= link_to create_path do 'Create' end %>
                    </li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Create new Blog</h3>
                    </div>

                    <%= form_for (@id), url: updateProgress_path do |f| %>
                    <div class="card-body">
                        
                        <div class="form-group">
                            <%= f.label 'Title', for: 'cbiTitle' %>
                            <%= f.text_field :blog_title, class: 'form-control', id: 'cbiTitle', placeholder: 'Title', required: '' %>
                        </div>
                        <div class="form-group">
                            <%= f.label 'Description', for: 'cbiDesc' %>
                            <%= f.text_area :blog_desc, class: 'form-control', id: 'cbiDesc', placeholder: 'Description', required: '' %>
                        </div>
                        <%= f.submit 'Save', name: 'submit', class: 'btn btn-primary btn-block' %>

                    </div>
                    <% end %>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ProjectMee</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-scrollbar-auto-hide="n" class="hold-transition sidebar-mini layout-fixed">
      <div class="wrapper">
        <%= render "components/header" %>
        <%= render "components/sidebar" %>

        <div class="content-wrapper">
          <%= yield %>
        </div>

        <%= render "components/footer" %>
        <%= render "components/control_sidebar" %>
      <div>
  </body>
</html>